jco.client.ashost=192.168.100.32
jco.client.sysnr=00
jco.client.client=001
jco.client.lang=EN

# jco.client.snc_lib=C:/foo/bar/baz/sapcrypto.dll

jco.client.snc_mode=1
jco.client.snc_sso=1
jco.client.snc_qop=3

jco.client.snc_partnername=p:CN=DEV-ABAP, O=Example, C=JP

# Specify this if multiple PSEs are configured for SSO.
# jco.client.snc_myname=p:CN=DEVELOPER, C=AR, O=TEST, OU=JP
